export const work = [
  {
    name: "SoundPage",
    description: "Link-in-bio tool for producers to sell kits and samples",
    href: "https://noahcousins.com",
    term: "2025",
    images: [
      "/projects/soundpage/1hero.png",
      "/projects/soundpage/2signin.png",
      "/projects/soundpage/3subscribe.png",
      "/projects/soundpage/4customize.png",
      "/projects/soundpage/5payout.png",
      "/projects/soundpage/6product.png",
      "/projects/soundpage/7products.png",
      "/projects/soundpage/soundpage.gif",
    ],
  },
  {
    name: "Drumify",
    description: "Sample marketplace for music producers",
    href: "https://www.drumify.com",
    term: "2022 - Present",
    images: [
      "/projects/drumify/1landing.png",
      "/projects/drumify/2browse.png",
      "/projects/drumify/3spotlight.png",
      "/projects/drumify/4sounds.png",
      "/projects/drumify/5filter.png",
      "/projects/drumify/drumify.gif",
    ],
  },
  {
    name: "Smyle Coffee",
    description: "Headless e-commerce for KYLE's coffee brand",
    href: "https://smylecoffee.com",
    term: "2025",
    images: [
      "/projects/smyle/1hero.png",
      "/projects/smyle/2products.png",
      "/projects/smyle/3smyle.png",
      "/projects/smyle/smyle.gif",
    ],
    darkButtons: true,
  },
];
