export const work = [
  {
    name: "Drumify",
    description: "Sample marketplace for music producers",
    href: "https://www.drumify.com",
    image: "/images/drumify.png",
    imageAlt: "Drumify",
    term: "2022 - Present",
    imageWidth: 1508,
    imageHeight: 854,
  },
  {
    name: "Smyle Coffee",
    description: "Headless e-commerce for KYLE's coffee brand",
    href: "https://smylecoffee.com",
    image: "/images/smyle.png",
    imageAlt: "Smyle Coffee",
    term: "2025",
    imageWidth: 1508,
    imageHeight: 854,
  },
  {
    name: "Postd",
    description: "Design & custom Webflow website for Postd",
    href: "https://postd.net",
    image: "/images/postd.png",
    imageAlt: "Postd",
    term: "2024",
    imageWidth: 1508,
    imageHeight: 854,
  },
];
